# Usa a imagem oficial do Flink como base
FROM flink:1.13.2-scala_2.12

# Instala o Python 3 e o pip dentro do container
# O comando '&&' garante que tudo rode em uma única camada para otimização
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip && \
    # Cria um "atalho" para que o comando 'python' chame o 'python3'
    ln -s /usr/bin/python3 /usr/bin/python